version: '3.8'
services:
  mencaldb:
    container_name: mencaldb
    image: postgres:15
    ports:
     - "5757:5432"
    environment:
     POSTGRES_DB: mencaldb
     POSTGRES_USER: mencalusr
     POSTGRES_PASSWORD: mencalpas
    volumes:
      - ./sql_scripts:/docker-entrypoint-initdb.d/